### 0 - Pytorch practice
https://www.learnpytorch.io/00_pytorch_fundamentals/

In [1]:
import torch
torch.cuda.is_available()

True

Set random seed

In [2]:
SEED = 0

Create random 7 by 7 tensor

In [3]:
torch.random.manual_seed(seed=SEED)
randtensor1 = torch.rand(7,7, device='cpu')
randtensor1

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])

In [4]:
randtensor1.device

device(type='cpu')

Perform a matrix multiplication

In [5]:
torch.random.manual_seed(seed=SEED)
randtensor2 = torch.rand(1,7, device='cpu')
randtensor2 = randtensor2.T
randtensor2

tensor([[0.4963],
        [0.7682],
        [0.0885],
        [0.1320],
        [0.3074],
        [0.6341],
        [0.4901]])

In [6]:
multtensor = torch.mm(randtensor1, randtensor2)
multtensor

tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])

Send tensors to GPU

In [7]:
CUDASEED = 1234

In [8]:
randtensor1gpu = randtensor1.to('cuda')
randtensor2gpu = randtensor2.to('cuda')
torch.cuda.manual_seed(seed=CUDASEED)
multtensorgpu = torch.mm(randtensor1gpu, randtensor2gpu)
multtensorgpu

tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]], device='cuda:0')

In [9]:
torch.manual_seed(seed=CUDASEED)
randtensor3 = torch.rand(2,3, device='cpu')
randtensor4 = torch.rand(2,3, device='cpu')
randtensor4 = randtensor4.T

randtensor3 = randtensor3.to('cuda')
randtensor4 = randtensor4.to('cuda')

multtensorgpu2 = torch.mm(randtensor3, randtensor4)
multtensorgpu2

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')

In [10]:
print(f"Min: {multtensorgpu2.min().item()}, Index: {multtensorgpu2.argmin().item()}")
print(f"Max: {multtensorgpu2.max().item()}, Index: {multtensorgpu2.argmax().item()}")

Min: 0.3647301495075226, Index: 0
Max: 0.5617256760597229, Index: 3


Reduce singular dimensions

In [11]:
torch.random.manual_seed(seed=SEED)
randtensor5 = torch.rand(1,1,1,10, device='cpu')
squeezedtensor = torch.squeeze(randtensor5)
print(randtensor5, randtensor5.shape)
print(squeezedtensor, squeezedtensor.shape)

tensor([[[[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901, 0.8964,
           0.4556, 0.6323]]]]) torch.Size([1, 1, 1, 10])
tensor([0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901, 0.8964, 0.4556,
        0.6323]) torch.Size([10])


In [12]:
randtensor5.dtype

torch.float32

Changing datatype

In [13]:
improved_precision = randtensor5.type(torch.float64)
improved_precision.dtype

torch.float64